"""add last_update

Revision ID: 1d6a9c121408
Revises: d931c0127130
Create Date: 2017-06-27 14:01:36.834432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d6a9c121408'
down_revision = 'd931c0127130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('last_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'last_update')
    # ### end Alembic commands ###
